# BroadcastPlugin Configuration

# Debug mode - set to true to enable additional logging
debug: false

# Categories settings
categories:
  # Enable message categories
  enabled: true

  # Directory where category configuration files are stored
  # Each file in this directory will be loaded as a separate message category
  directory: "categories"

  # Default settings for categories (used if not specified in the category file)
  defaults:
    # Interval between messages in minutes
    interval: 5

    # Appearance settings
    appearance:
      # Separator line displayed before and after messages
      separator: "------------------------------"
      # Enable clickable links in messages
      enable_clickable_links: true

    # Message order settings
    order:
      # Randomize message order instead of sequential
      randomize_messages: false

# Legacy broadcast settings (used if categories are disabled)
# This is kept for backward compatibility
broadcast:
  # Interval between messages in minutes
  interval: 5

  # Appearance settings
  appearance:
    # Separator line displayed before and after messages
    separator: "------------------------------"
    # Enable clickable links in messages
    enable_clickable_links: true

  # Message order settings
  order:
    # Randomize message order instead of sequential
    randomize_messages: false

  # Messages to broadcast
  # You can use color codes with § symbol
  # Use \n for new lines
  messages:
    - "§6Join our Discord community!\n§7Stay updated with server development plans and announcements.\n§6Link: §7https://discord.gg/NuDQ8UUu7f"
    - "§6Use §7/whodoq §6to check who is currently occupying a dungeon on a specific difficulty level!"
    - "§6Curious about the top players? Use §7/top §6to see the leaderboard of the top 10 players with the highest levels."
    - "§6Want to team up? Use §7/party §6to create or join a party (up to 3 players).\n§7Earn extra rewards! If a party member kills a mob within 25 blocks, you gain an additional §630% EXP§7 for that mob!"
    - "§6See someone cheating or find a bug?\n§7Please report cheaters and any bugs you find to the server administrators.\n§6Your help keeps the server fair and enjoyable for everyone! §7Thank you for supporting our community!"
    - "§6Curious about boss souls?\n§7Enhance your power by equipping powerful souls and unleash their hidden abilities!\n§6Link: §7https://dsocraft.pl/bossouls.php"
    - "§6Curious about jewels?\n§7Enhance your gameplay by equipping unique jewels with special abilities!\n§6Link: §7https://dsocraft.pl/jewels.php"
